server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secforgtek_lms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC

app:
  jwt:
    secret: "change-this-super-secret-key-please"
    expiration-minutes: 240
  seed:
    admin-email: admin@secforgtek.com
    admin-password: Admin123!

springdoc:
  swagger-ui:
    path: /swagger-ui.html
